branches:
  only:
    - master
    - develop

language: php

php:
  - '5.6'

before_script:
  - echo 'travis-test'

script:
  - echo exec-script
  - ./test.sh 100 hoge

after_script:
  - echo 'after-script'
